# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target ‘MedlyDemo’ do

pod 'SnapKit', '~> 3.0'
pod 'Locksmith', '~> 3.0'
pod 'Google/Analytics'
pod 'libPhoneNumber-iOS', '~> 0.8'
end

target 'MedlyDemoTests' do

end

post_install do |installer|
  installer.pods_project do |pods|
    pods.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
    end
  end
end

